spring:
  application:
    name: SocksOrder
  schedule:
    deadline-by-year: 5
    cron: "0 0 0 0 *"

  datasource:
    url: {DB_URI:jdbc:postgresql://127.0.0.1:6432/order_service}
    username: {DB_USER:postgres}
    password: {DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

server:
  port: 2010